# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test
      run: |
        pytest flask_app/test_calculator.py
    - name: build app
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --onefile --add-data 'flask_app/templates:flask_app/templates' --add-data 'static:static' flask_app/calculator.py
        mkdir -p dist
        mv app.spec dist/
        mv dist/app.spec dist/app
        cp -r flask_app dist/
        
    
    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        
    
        
